### ISSUE TITLE
Adding a scenario with multiple changes in variables

### ISSUE THREAD

**Issue by TheMKVL** [S120/PKSFC#3]
Dear fellow PKSFC-users,

I am wondering, if it is possible to use the add.Scenario function and change multiple variables at the same time, i.e. simulating some sort of policy mix. I have tried the following command:

`model1 <- sfc.addScenario(model = model1, vars = c("G","N"), values = c(10.2,105), inits = 1960, ends = 2010, starts = init)`

This is essentially a simultaneous shock to labour force AND government expenditure. However, when simulating I receive:

`> datamodel1<-simulate(model1)
Error in seq.default(from = model$time[1], to = scen$init) : 
  'to' cannot be NA, NaN or infinite`

On the other hand, applying the shocks separately to the model works perfectly fine.

Of course, I can post/send the entire code and model at request, if necessary.

**Comment by antoinegodin** [comment]
Hi TheMKVL,

In order to add multiple shocks at once, you need to use lists to encapsulate the variables you want to shock. Your code should hence look like this:

`model1 <- sfc.addScenario(model = model1, vars = list(c("G","N")), values = list(c(10.2,105)), inits = 1960, ends = 2010, starts = init)`

I hope this helps.

**Comment by TheMKVL** [comment]
Dear Prof. Godin,
Thanks for this quite simple solution - I am still learning R. But so far, the PKSFC package helps tremendously!
